server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/book}
    #    url: ${DBMS_CONNECTION:jdbc:mysql://host.docker.internal:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:Kieuhieu2@}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

dubbo:
  application:
    name: book-service
  registry:
    address: zookeeper://localhost:2181

  consumer:
    timeout: 3000
logging:
  level:
    org.apache.dubbo: DEBUG
    org.apache.dubbo.rpc: DEBUG

